name: Build yearly planner

on:
  schedule:
    - cron: "0 0 1 12 *"
  workflow_dispatch:
  push:
    paths:
      - "config/template/**" # templates changed
      - ".github/workflows/yearly-planner.yml"

jobs:
  planner:
    runs-on: ubuntu-latest
    container:
      image: pandoc/typst:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - run: apk add --no-cache git ghostscript ttf-firacode
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
      - run: bash setup.sh
      - uses: actions/upload-artifact@v4
        with:
          name: planner-$(date +%Y%m%d)
          path: out/*.pdf
